# Generated by Django 3.2.4 on 2021-07-07 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('IN', 'Интернет'), ('TV', 'ТВ каналы')], default='IN', max_length=2, verbose_name='Тип тарифа')),
                ('netup_tariff_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Tariff ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название тарифа')),
                ('netup_tariff_link_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Tariff link ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='netup_account_id',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Биллинг айди'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='TariffRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.customer')),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tariff', verbose_name='Тариф')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tariffs',
            field=models.ManyToManyField(blank=True, through='content.TariffRelation', to='content.Tariff'),
        ),
    ]
