# Generated by Django 3.2.4 on 2021-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_customer_netup_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='cost',
            field=models.PositiveIntegerField(blank=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание тарифа'),
        ),
    ]
