# Generated by Django 3.2.4 on 2021-07-09 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_tariff_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_id', models.PositiveIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.customer')),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tariff', verbose_name='Тариф')),
            ],
        ),
        migrations.DeleteModel(
            name='TariffRelation',
        ),
        migrations.AlterField(
            model_name='customer',
            name='tariffs',
            field=models.ManyToManyField(blank=True, through='content.Subscription', to='content.Tariff'),
        ),
    ]
