# Generated by Django 3.2.4 on 2021-07-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210709_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='netup_tariff_link_id',
        ),
    ]
