# Generated by Django 3.2.4 on 2021-07-09 09:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_tariff_netup_tariff_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Имеил'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
