# Generated by Django 3.2.4 on 2021-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210709_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='instant_change',
            field=models.BooleanField(blank=True, default=True, verbose_name='Сразу ли сменится'),
            preserve_default=False,
        ),
    ]
