# Generated by Django 3.2.4 on 2021-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_tariff_instant_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='instant_change',
            field=models.BooleanField(blank=True, null=True, verbose_name='Сразу ли сменится'),
        ),
    ]
