# Generated by Django 3.2.4 on 2021-07-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_customer_netup_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.customer'),
        ),
    ]
